const API_KEY = 'bf5acf81f81c091e4cda77114f6c6287';
const DEFAULT_CITY = 'Vitória';
const citiesES = ['Afonso Cláudio','Água Doce do Norte','Águia Branca','Alegre','Alfredo Chaves','Alto Rio Novo','Anchieta','Apiacá','Aracruz','Atilio Vivacqua','Baixo Guandu','Barra de São Francisco','Boa Esperança','Bom Jesus do Norte','Brejetuba','Cachoeiro de Itapemirim','Cariacica','Castelo','Colatina','Conceição da Barra','Conceição do Castelo','Divino de São Lourenço','Domingos Martins','Dores do Rio Preto','Ecoporanga','Fundão','Governador Lindenberg','Guaçuí','Guarapari','Ibatiba','Ibiraçu','Ibitirama','Iconha','Irupi','Itaguaçu','Itapemirim','Itarana','Iúna','Jaguaré','Jerônimo Monteiro','João Neiva','Laranja da Terra','Linhares','Mantenópolis','Marataízes','Marechal Floriano','Marilândia','Mimoso do Sul','Montanha','Mucurici','Muniz Freire','Muqui','Nova Venécia','Pancas','Pedro Canário','Pinheiros','Piúma','Ponto Belo','Presidente Kennedy','Rio Bananal','Rio Novo do Sul','Santa Leopoldina','Santa Maria de Jetibá','Santa Teresa','São Domingos do Norte','São Gabriel da Palha','São José do Calçado','São Mateus','São Roque do Canaã','Serra','Sooretama','Vargem Alta','Venda Nova do Imigrante','Viana','Vila Pavão','Vila Valério','Vila Velha','Vitória'];
const $ = s => document.querySelector(s);
const statusEl = $('#weatherStatus');
function icon(code){return code ? `https://openweathermap.org/img/wn/${code}@2x.png` : ''}
function dateBR(d){return new Intl.DateTimeFormat('pt-BR',{weekday:'short',day:'2-digit',month:'short'}).format(d).replace('.','')}
function status(msg,type=''){statusEl.textContent=msg;statusEl.className=`status-card ${type}`}
function label(s=''){return s.charAt(0).toUpperCase()+s.slice(1)}
function insight(t,h,r){if(r>=50)return ['Chuva no radar','A previsão indica maior chance de precipitação. Combine a previsão com as condições reais do solo e da lavoura.','🌧️ Atenção à chuva'];if(h>=80)return ['Ambiente mais úmido','Umidade elevada pede atenção ao microclima da lavoura e ao monitoramento fitossanitário.','💧 Monitorar umidade'];if(t>=32)return ['Temperatura elevada','Dias mais quentes podem aumentar a demanda hídrica. Monitore a lavoura e a disponibilidade de água.','🌡️ Atenção ao calor'];if(t<=18)return ['Temperatura amena','Condições mais amenas alteram o ritmo fisiológico do cafeeiro. Observe a evolução do tempo.','⛰️ Clima ameno'];return ['Condições estáveis','Use a previsão como apoio ao planejamento e acompanhe também as condições específicas da propriedade.','🌱 Monitoramento']}
function recs(days){const at=days.reduce((s,d)=>s+d.temp,0)/days.length, ah=days.reduce((s,d)=>s+d.humidity,0)/days.length, rp=Math.max(...days.map(d=>d.pop)), mm=days.reduce((s,d)=>s+d.rain,0);$('.recommendation:nth-child(1) p').textContent=at>=32?'Temperaturas médias elevadas. Observe a disponibilidade hídrica e o comportamento da lavoura.':at<=18?'Temperaturas médias mais baixas. Acompanhe a evolução do clima e o estágio da lavoura.':'Temperaturas intermediárias. Continue acompanhando a previsão antes das operações de campo.';$('.recommendation:nth-child(2) p').textContent=ah>=80?'Umidade média elevada. Intensifique o monitoramento das condições do cafezal e do microclima.':ah<55?'Umidade média mais baixa. Avalie as condições do solo e a necessidade de irrigação conforme o manejo adotado.':'Umidade média moderada. Observe a combinação entre umidade, temperatura e chuva.';$('.recommendation:nth-child(3) p').textContent=rp>=60||mm>=20?`Há sinal de chuva no período (até ${rp}% de probabilidade em um dos dias). Planeje atividades considerando a previsão.`:'A previsão indica menor ocorrência de chuva. Para irrigação, considere também a umidade do solo e o manejo da propriedade.'}
async function getWeather(city){status('Consultando condições meteorológicas...','loading');try{const [a,b]=await Promise.all([fetch(`https://api.openweathermap.org/data/2.5/weather?q=${encodeURIComponent(city)},BR&appid=${API_KEY}&lang=pt_br&units=metric`),fetch(`https://api.openweathermap.org/data/2.5/forecast?q=${encodeURIComponent(city)},BR&appid=${API_KEY}&lang=pt_br&units=metric`)]);if(!a.ok||!b.ok)throw Error('not found');const cur=await a.json(), fc=await b.json();renderCurrent(cur);const days=group(fc.list);renderForecast(days);recs(days);const i=insight(cur.main.temp,cur.main.humidity,Math.max(...days.map(d=>d.pop)));$('#agroTitle').textContent=i[0];$('#agroText').textContent=i[1];$('#agroPill').textContent=i[2];status(`Atualizado para ${cur.name}, Espírito Santo.`,'success')}catch(e){console.error(e);status('Não foi possível consultar esta cidade. Verifique o nome e tente novamente.','error')}}
function renderCurrent(d){$('#weatherCity').textContent=`${d.name}, ES`;$('.weather-icon').src=icon(d.weather?.[0]?.icon);$('.weather-icon').alt=label(d.weather?.[0]?.description||'Condição atual');$('.temp').textContent=`${Math.round(d.main.temp)}°`;$('.desc').textContent=label(d.weather?.[0]?.description||'');$('.sensTermica').textContent=`Sensação térmica ${Math.round(d.main.feels_like)}°C`;$('.umidade').textContent=`${d.main.humidity}%`;$('.pressao').textContent=`${d.main.pressure} hPa`;$('.vento').textContent=`${Math.round(d.wind.speed*3.6)} km/h`}
function group(list){const g={};list.forEach(x=>{const k=x.dt_txt.split(' ')[0];(g[k]??=[]).push(x)});return Object.entries(g).slice(0,5).map(([date,it])=>({date:new Date(`${date}T12:00:00`),min:Math.min(...it.map(x=>x.main.temp_min)),max:Math.max(...it.map(x=>x.main.temp_max)),temp:it.reduce((s,x)=>s+x.main.temp,0)/it.length,humidity:it.reduce((s,x)=>s+x.main.humidity,0)/it.length,pop:Math.round(Math.max(...it.map(x=>(x.pop||0)*100))),rain:it.reduce((s,x)=>s+(x.rain?.['3h']||0),0),icon:it[Math.floor(it.length/2)]?.weather?.[0]?.icon||it[0]?.weather?.[0]?.icon,description:it[Math.floor(it.length/2)]?.weather?.[0]?.description||''}))}
function renderForecast(days){$('#forecast').innerHTML=days.map(d=>`<article class="forecast-card"><div class="forecast-date">${dateBR(d.date)}</div><img src="${icon(d.icon)}" alt="${label(d.description)}"><div class="forecast-temp"><strong>${Math.round(d.max)}°</strong><span>${Math.round(d.min)}°</span></div><p>${label(d.description)}</p><div class="forecast-meta"><span>💧 ${Math.round(d.humidity)}%</span><span>🌧️ ${d.pop}%</span></div><small>${d.rain.toFixed(1)} mm previstos</small></article>`).join('')}
const list=$('#cities');citiesES.forEach(c=>{const o=document.createElement('option');o.value=c;list.appendChild(o)});$('#cityForm').addEventListener('submit',e=>{e.preventDefault();const c=$('#city').value.trim();if(c)getWeather(c)});function clock(){$('#clock').textContent=new Intl.DateTimeFormat('pt-BR',{hour:'2-digit',minute:'2-digit'}).format(new Date())}setInterval(clock,1000);clock();$('#city').value=DEFAULT_CITY;getWeather(DEFAULT_CITY);
